version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=airbyte
    networks:
      - airbyte_airbyte_internal

networks:
  airbyte_airbyte_internal:
    external: true
    name: airbyte_airbyte_internal
